name: Deploy Extension
on:
  push:
    tags:
      - v*

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install vsce
        run: npm install -g vsce
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: vsce package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: "*.vsix"
  publish:
    needs: upload-artifact
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Install vsce
        run: npm install -g vsce
      - name: Publish
        run: vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
