name: Update packages
on: workflow_dispatch
jobs:
  update:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm update --save
      - run: node tools/syncVscodeVersion.mjs
      - name: git status
        id: git_status
        run: '[ -n "`git status -s`" ]'
        continue-on-error: true
      - name: Start xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        shell: bash
        if: steps.git_status.outcome == 'success'
      - run: npm test
        env:
          DISPLAY: ':99.0'
        if: steps.git_status.outcome == 'success'
      - name: get updated modules
        run: |
          echo "diff<<EOF" >> "$GITHUB_OUTPUT"
          git diff package.json | grep -E '^\+ ' | sed 's/[",^+]//g' >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        id: updated_modules
        if: steps.git_status.outcome == 'success'
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Update package
            
            ${{ steps.updated_modules.outputs.diff }}
        if: steps.git_status.outcome == 'success'
